services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - spend-track-network
    volumes:
      - postgres:/var/lib/postgres/data
  spend-track-app:
    container_name: spend-track-container
    image: ajimad/spend-tracker-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spend-track-network

volumes:
  postgres:

networks:
  spend-track-network:
    driver: bridge