spring:
  datasource:
    url: @db_prod_url@
    username: @db_prod_username@
    password: @db_prod_password@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: @db_prod_username@
    password: @db_prod_password@
    baseline-description: "init"
    baseline-version: 1